version: 2
run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
